name: benchmarks

on:
  push:
    branches:
      - "main-x"
  #     - "main"
  # pull_request:
  # # `workflow_dispatch` allows CodSpeed to trigger backtest
  # # performance analysis in order to generate initial data.
  # workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - uses: mkroening/rust-toolchain-toml@main
      - uses: extractions/setup-just@v2
      - name: Prep build venv
        shell: bash
        run: |
          uv venv -p 3.12 venv/
          . venv/bin/activate
          uv pip sync --strict requirements/build-py3.12.txt
      - name: Build wheel
        shell: bash
        run: |
          . venv/bin/activate
          just build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            . venv/bin/activate
            WHEEL_FILE=$(ls ./dist/*.whl)
            uv pip install -v --no-deps $WHEEL_FILE
            just test-benchmark
